import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import { useAuth } from '../context/AuthContext'
import UserDashboard from '../components/UserDashboard'

export default function Home() {
  const {currentUser} = useAuth()
  //console.log(currentUser)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <i className="fa-solid fa-dragon"></i>
      {!currentUser && <Login />}
      {currentUser && <UserDashboard/>}
    </>
  )
}
